version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.....
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_URI/$ECR_REPO:latest .
      - docker tag $ECR_URI/$ECR_REPO:latest $ECR_URI/$ECR_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images....
      - docker push $ECR_URI/$ECR_REPO:latest
      - docker push $ECR_URI/$ECR_REPO:$IMAGE_TAG
      - printf '[{"name":"ui","imageUri":"%s"}]' "$ECR_URI/$ECR_REPO:$IMAGE_TAG" > images.json
      - cat images.json

artifacts:
  files:
    - images.json